# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk11
  - openjdk12

install: true
script: ./mvnw clean install

before_install:
  - chmod +x mvnw